# Generated by Django 4.2.23 on 2025-07-21 09:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ara_ako', '0002_auto_20220406_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='araakoteam',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
