# Generated by Django 4.2.20 on 2025-04-03 01:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('get_started', '0004_alter_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='video_transcript',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
