# Generated by Django 4.2.20 on 2025-04-03 01:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0007_auto_20220406_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
