# Generated by Django 4.2.23 on 2025-07-21 09:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0015_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
