# Generated by Django 4.2.20 on 2025-04-03 01:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20220406_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
