# Generated by Django 4.2.20 on 2025-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='institution_address',
            field=models.TextField(default='123 Fakestreet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='institution_name',
            field=models.CharField(default='Made up institution', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_paid_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_category',
            field=models.CharField(choices=[('standard', '1 person Membership $50'), ('student_teacher', 'Student Teacher (Free)'), ('primary', 'Primary (Free)'), ('year_7_8', 'Year 7-8 (Free)'), ('kura_kaupapa', 'Kura Kaupapa (Free)'), ('wider_sector', 'Wider Education Sector')], default='standard', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='membership_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
